version: "3.8"

services:
  nginx:
    container_name: nginx-container
    build: ./requirements/nginx/.
    ports:
      - "8080:443"
  wordpress:
    container_name: wp-container
    build: ./requirements/wordpress/.
    ports:
      - "9000:9000"
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
  mariadb:
    container_name: mariadb-container
    build: ./requirements/mariadb/.
    ports:
      - "3306:3306"