services:
  nginx:
    container_name: nginx-container
    build: ./requirements/nginx/.
    networks:
      - my-network
    ports:
      - "8080:443"
    volumes:
      - wp-data:/var/www/html/
  wordpress:
    container_name: wp-container
    build: ./requirements/wordpress/.
    networks:
      - my-network
    ports:
      - "9000:9000"
    volumes:
      - wp-data:/var/www/html/
      - ./requirements/wordpress/wp-config.php:/var/www/html/wp-config.php
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
  mariadb:
    container_name: mariadb-container
    build: ./requirements/mariadb/.
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./requirements/mariadb/my.cnf:/etc/mysql/my.cnf
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
volumes:
  db-data:
  wp-data: