services:
  mariadb:
    restart: always
    container_name: mariadb-container
    build: ./requirements/mariadb/.
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - my-network
  wordpress:
    restart: always
    depends_on:
      - mariadb
    container_name: wp-container
    build: ./requirements/wordpress/.
    networks:
      - my-network
    ports:
      - "9000:9000"
    volumes:
      - wp-data:/var/www/html/
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
  nginx:
    restart: always
    depends_on:
      - wordpress
    container_name: nginx-container
    build: ./requirements/nginx/.
    networks:
      - my-network
    ports:
      - "8080:443"
    volumes:
      - wp-data:/var/www/html/
networks:
  my-network:
volumes:
  db-data:
  wp-data: